### ISSUE TITLE
Try turn on eslint `@typescript-eslint/padding-line-between-statements`

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#1686]
To ensure consistent readability across multiple contributors and prevent writing reviews like "pls add a blank line here" we want to try to turn on and configure https://typescript-eslint.io/rules/padding-line-between-statements/

# TODO

- [x] after blocks https://github.com/faker-js/faker/pull/1691
- [ ] before blocks https://github.com/faker-js/faker/pull/1703
- [ ] between cases (switch-case)

**Comment by ST-DDT** [comment]
I'm not against adding the rule, but from their page:

![20221225_170510](https://user-images.githubusercontent.com/1579362/209474906-e9c413a5-e780-4c5b-887c-63d9341d3dc8.jpg)

**Comment by Shinigami92** [comment]
@ST-DDT please note that this message appears for everyone visiting the page and I know why they are saying this
But please provide an alternative proposal for a solution for the issue described in the description of this issue or provide other reasons why you think it is important to explicitly double express this warning message from their site

I know that prettier doesn't have any kind of option to fulfill our needs but also know that I'm tired of writing review comments for this over and over again

**Comment by ST-DDT** [comment]
As I said, I'm not against this rule.

I just dont know what this rule does exactly.

- The linked page does not contain an example
- I dont know how/whether this will impact our code
- I dont remember any instance where that was an issue.

I personally prefer PRs for "do something tiny" over issue + PRs.

Also in context of #1683

**Comment by Shinigami92** [comment]
> The linked page does not contain an example

`@typescript-eslint` reflects many native rules and therefore for examples you need to look into the native one: https://eslint.org/docs/latest/rules/padding-line-between-statements

But this is basically the first paragraph in the [examples](https://typescript-eslint.io/rules/padding-line-between-statements/#examples)

> I personally prefer PRs for "do something tiny" over issue + PRs.

I'm okay with that you personally prefer this and cant do anything against your preference,
but I would like to drive Faker as an Open Source project where anyone is welcome to contribute
It is hard to contribute to a project when you don't know what is currently available to contribute
Issues make this more open to the community

In addition to that, I don't have always the time to instantly tackle something and therefore instead of making my own note block full with anykind of potential things I can do, I like to help myself with issues so I can better remember what I wanted to do all kind of things

**Comment by EarthyOrange** [comment]
@Shinigami92 The "What about formatting?" linked page from @ST-DDT 's screenshot recommends configuring adding blank lines using a formatter instead of a linter. I see that this project uses the Prettier formatter; can you attempt following the recommendation and use the formatter to drive this formatting?

**Comment by Shinigami92** [comment]
@EarthyOrange I'm sorry but prettier does not have such an option
If I'm wrong please tell me how you can configure prettier to do that

Edit: you can even read that on prettier website: https://prettier.io/docs/en/rationale.html#empty-lines

**Comment by EarthyOrange** [comment]
@Shinigami92 No, you are right; Prettier has stopped dealing with blank lines. You will have to use the linter to add blank lines.

**Comment by xDivisionByZerox** [comment]
Is this still active or do we consider this done as #1691 has been merged? I see the other TODO's but would consider them obsolete.

**Comment by Shinigami92** [comment]
> Is this still active or do we consider this done as #1691 has been merged? I see the other TODO's but would consider them obsolete.

Please see https://github.com/faker-js/faker/pull/1703#issuecomment-1368210435 for more details

**Comment by xDivisionByZerox** [comment]
> Please see [#1703 (comment)](https://github.com/faker-js/faker/pull/1703#issuecomment-1368210435) for more details

Thats exactly why I consider these remaining doings obsolte. I'm with the comment made in https://github.com/typescript-eslint/typescript-eslint/issues/6291#issuecomment-1579893486.

**Comment by Shinigami92** [comment]
Looks like I'm turning back to writing "pls add a blank line here" in reviews 🤷
