### ISSUE TITLE
Release Checklist v8.4.1

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2645]
The "final" release for v8.x

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Check for open PRs that could/should be included
- [x] Update dependencies, if possible
- [x] Checkout next, Pull latest commits, revert all uncommited changes, and force fetch all tags
- [x] Check project with playground(s) via `pnpm.overrides`
  - [x] https://github.com/faker-js/playground
- [x] Create release branch
- [x] `pnpm release` (bumps version and generates changelog)
- [x] Remove dummy release tag 
- [x] Create Release PR

**Post-Release ToDos**

- [x] Publish release on npm
- [x] Create Release on GitHub
- [x] Push latest commits to vX branch
- [x] Update and test release version with playground(s) (no `pnpm.overrides`)
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)
- [x] Set `next` npm dist-tag

**One Week Later ToDos**

- [x] Set `stable` npm dist-tag
- [x] Close vX milestone, if applicable
- [ ] ~~Change version to v9.0-alpha.0 ❓~~
- [x] Amend this list with missing items
