### ISSUE TITLE
Release Checklist v9.0.0-alpha.0

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#2807]
The release for `v9.0.0-alpha.0`

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Update Migration Guide
- [x] Checkout next, Pull latest commits, revert all uncommited changes, and force fetch all tags
- [x] Check project with playground(s) via `pnpm.overrides`
  - [x] https://github.com/faker-js/playground
- [x] Create release branch
- [x] `pnpm release` (bumps version and generates changelog)
- [x] Remove dummy release tag 
- [x] Create Release PR

**Post-Release ToDos**

- [x] Publish release on npm
- [x] Create Release on GitHub
- [x] Push latest commits to vX branch
- [x] (Temporarily) Test release version with playground(s) (no `pnpm.overrides`)
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)
- [x] Set `next` npm dist-tag
- [x] Redeploy netlify production branch (to update the version selector)

**Comment by xDivisionByZerox** [comment]
v9 required a TypeScript version of at least 5. The playground needs an update:

- https://github.com/faker-js/playground/pull/6
