### ISSUE TITLE
Release Checklist v9.0.0-alpha.1

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#2966]
The release for `v9.0.0-alpha.1`

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Update Migration Guide
- [x] Check for mergeable PRs/dependency updates
- [x] Checkout next, Pull latest commits, revert all uncommited changes, and force fetch all tags
- [x] Check project with playground(s) via `pnpm.overrides`
  - [x] https://github.com/faker-js/playground
- [x] Create release branch `chore/release/v9.0.0-alpha.1`
- [x] `pnpm release` (bumps version and generates changelog)
- [x] Create Release PR `chore(release): v9.0.0-alpha.1`

**Release ToDos**

- [x] Merge Release PR
- [x] Checkout/Pull the release commit, revert/stash all uncommited changes
- [x] Remove `⚠️ You are reading the docs for the next branch ⚠️` from README without committing
- [x] Publish release on npm
- [x] Push latest commits to `v9` branch
- [x] Test release version with playground(s) (no `pnpm.overrides`) (only temporarily) 
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)
- [x] Set `next` npm dist-tag
- [x] Redeploy Netlify production branch (to update the version selector)
- [x] Re-crawl with Algolia crawler
- [x] Create Release on GitHub

**Comment by ST-DDT** [comment]
Deployment successful
