### ISSUE TITLE
Release Checklist v9.0.0-rc.0

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#3005]
The release for `v9.0.0-rc.0`

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Update Migration Guide
- [x] Check for mergeable PRs/dependency updates
- [x] Checkout next, Pull latest commits, revert all uncommited changes, and force fetch all tags
- [x] Check project with playground(s) via `pnpm.overrides`
  - [x] https://github.com/faker-js/playground
- [x] Create release branch `chore/release/vX`
- [x] `pnpm run release --prerelease` (bumps version and generates changelog)
- [x] Create Release PR `chore(release): vX...`

**Release ToDos**

- [x] Merge Release PR
- [x] Checkout/Pull the release commit, revert/stash all uncommited changes
- [x] Remove `⚠️ You are reading the docs for the next branch ⚠️` from README without committing
- [x] Publish release on npm `pnpm publish --tag next --no-git-checks`
- [x] Push latest commits to `vX` branch
- [x] Test release version with playground(s) (no `pnpm.overrides`) (only temporarily) 
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)
- [x] Create Release on GitHub
- [x] Clean cache and redeploy Netlify production branch (to update the version selector)
- [x] Re-crawl with Algolia crawler
