### ISSUE TITLE
Release Checklist v9.0.0-rc.1

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#3066]
The release for `v9.0.0-rc.1`

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Check for mergeable PRs/dependency updates
- [x] Create Release PR via [GitHub Actions](https://github.com/faker-js/faker/actions/workflows/prepare-release-pr.yml)
  - [x] Link Release PR with this issue
- [x] Push any manual changes to the release branch/PR
- [x] Mark PR as ready for review

**Release ToDos**

- [x] Merge Release PR
- [x] Test release version with playground(s) (no `pnpm.overrides`)
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)
- [x] Clean cache and redeploy Netlify production branch (to update the version selector)
- [x] Re-crawl with [Algolia crawler](https://crawler.algolia.com/)
- [x] Publish [Release on GitHub](https://github.com/faker-js/faker/releases)
