### ISSUE TITLE
Release Checklist v9.0.0

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#3085]
The release for `v9.0.0`

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Update Migration Guide
- [x] Check for mergeable PRs/dependency updates
- [x] Create Release PR via [GitHub Actions](https://github.com/faker-js/faker/actions/workflows/prepare-release-pr.yml)
  - [x] Link Release PR with this issue
- [x] Update redirects in [`netlify.toml#L20`](https://github.com/faker-js/faker/blob/next/netlify.toml#L20)
- [x] Update Readme [Version Table](https://github.com/faker-js/faker/blob/next/README.md?plain=1#L27-L31)
- [x] Update Readme [Module Info Versions](https://github.com/faker-js/faker/blob/next/README.md?plain=1#L84)
- [x] Update [docs/guide/usage.md version pin](https://github.com/faker-js/faker/blob/next/docs/guide/usage.md?plain=1#L59)
- [x] Push any manual changes to the release branch/PR
- [x] Mark PR as ready for review
- [x] Prepare release announcement => Awaiting merge of #3056

**Release ToDos**

- [x] Change [netlify production branch](https://app.netlify.com/sites/fakerjs/configuration/deploys#branches-and-deploy-contexts)
- [x] Merge Release PR
- [x] Test release version with playground(s) (no `pnpm.overrides`)
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)
- [x] Set `old` npm dist-tag to previous major
- [x] Re-crawl with [Algolia crawler](https://crawler.algolia.com/)
- [x] Publish [Release on GitHub](https://github.com/faker-js/faker/releases)
- [x] Publish Release Announcement

**Post-Release ToDos (1 week later)**

- [ ] ~~Set `stable` npm dist-tag~~
- [x] Close v9.0 milestone
