### ISSUE TITLE
Release Checklist v9.0.1

### ISSUE THREAD

**Issue by Shinigami92** [faker-js/faker#3110]
The release for `v9.0.1`

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Check for mergeable PRs/dependency updates
- [x] Create Release PR via [GitHub Actions](https://github.com/faker-js/faker/actions/workflows/prepare-release-pr.yml)
  - [x] Link Release PR with this issue
- [x] Update [docs/guide/usage.md version pin](https://github.com/faker-js/faker/blob/next/docs/guide/usage.md?plain=1#L77)
- [x] Push any manual changes to the release branch/PR
- [x] Mark PR as ready for review

**Release ToDos**

- [x] Merge Release PR
- [x] Publish [Release on GitHub](https://github.com/faker-js/faker/releases)
- [x] Re-crawl with [Algolia crawler](https://crawler.algolia.com/)
- [x] Test release version with playground(s) (no `pnpm.overrides`)
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)

**Post-Release ToDos (1 week later)**

- [x] Set `stable` npm dist-tag

**Comment by Shinigami92** [comment]
@ST-DDT we got a CI error on the last step

<img src="https://github.com/user-attachments/assets/6cb0d710-317f-4dec-b831-bf18ca178b9f" width="500px" />

https://github.com/faker-js/faker/actions/runs/10865127199/job/30151223985#step:11:14

**Comment by ST-DDT** [comment]
Fixed in branch protection settings.
