### ISSUE TITLE
Release Checklist v9.0.2

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#3139]
The release for `v9.0.2`

**Pre-Release ToDos**

- [x] Create new `Release Checklist` issue
- [x] Check for mergeable PRs/dependency updates
- [x] Create Release PR via [GitHub Actions](https://github.com/faker-js/faker/actions/workflows/prepare-release-pr.yml)
  - [x] Link Release PR with this issue
- [x] Update [docs/guide/usage.md version pin](https://github.com/faker-js/faker/blob/next/docs/guide/usage.md?plain=1#L77)
- [x] Push any manual changes to the release branch/PR
- [x] Mark PR as ready for review

**Release ToDos**

- [x] Merge Release PR
- [x] Publish [Release on GitHub](https://github.com/faker-js/faker/releases)
- [x] Re-crawl with [Algolia crawler](https://crawler.algolia.com/)
- [x] Test release version with playground(s) (no `pnpm.overrides`)
  - [x] https://github.com/faker-js/playground
  - [x] [stackblitz](https://stackblitz.com/edit/faker-js-demo?file=index.ts)

**Post-Release ToDos (1 week later)**

- [x] Set `stable` npm dist-tag

**Comment by ST-DDT** [comment]
Release Provenance is working 🎉 

![grafik](https://github.com/user-attachments/assets/7a698e96-97eb-45a7-bc0f-070cdcb9716d)
