### ISSUE TITLE
Release v6.0.0 Roadmap

### ISSUE THREAD

**Issue by ST-DDT** [faker-js/faker#542]
This is our planned roadmap to v6.0.0.

Feel free to suggest changes or report important bugs/incompatibilities.

1. Fix remaining todos
  - [x] Fix JSDocs #203 / #562 (@ST-DDT )
  - [x] Do another pass on the docs/search for typos/style issues #514 (@ST-DDT)
  - [x] Tree-shaking not properly documented #405 / #549 (@Shinigami92 )
  - [ ] ~Vet v6.0.0-alpha.x types emitted types against v5.5.3 #305 (**Not yet assigned**)~
  - [x] Fix time.recent method signature #586 (@ST-DDT)
2. ✅ Release v6.0.0-beta.1/rc.1 (Early March) 
3. ✅ Migrate some well known libraries to fakerjs (to test compatibility)
4. ✅ Wait a week or two for feedback
5. ✅ Release v6.0.0 (~Mid March)
6. ✅ Freeze for potential v6.0.x bug fixes (1 week)
7. ✅ Close v6.0.x release window and start development of v6.1.0. (Late March)

**Comment by Shinigami92** [comment]
Some top repos using faker

- https://github.com/freeCodeCamp/freeCodeCamp/blob/5d30bb6cd5b72105c43beb562ea52dcbb30dad01/package.json#L158
- https://github.com/vercel/next.js/blob/b25f7f84b1e638a8564805a5bdc0d77ae5244d0b/package.json#L110
- https://github.com/supabase/supabase/blob/e2e5ce463aa906af634cb3ae7d033e704cf746eb/package.json#L28
- https://github.com/pubkey/rxdb/blob/4f5528879993293ea77dcc91c0139f9f4427667b/package.json#L197
- https://github.com/directus/directus/blob/a8df6d96531fea4ee747594d0b047d2a676714be/package.json#L44
- https://github.com/krisk/Fuse/blob/30f1026fe171699db4a7cd12f7f40a32466f4ee1/package.json#L80
- https://github.com/segmentio/evergreen/blob/505258cdd8a23f3822fed7a7e9570215e8c7488e/package.json#L126
- https://github.com/alan2207/bulletproof-react/blob/f3b2be7278a5808885b917a17e6323cc4d16700f/package.json#L116

**Comment by ST-DDT** [comment]
I will go for https://github.com/hashicorp/consul/blob/main/ui/packages/consul-ui/package.json

**Comment by connorjs** [comment]
I saw y'all released v6.0.0 - just wanted to say A W E S O M E and THANK YOU to everyone involved in all of this 🤩

**Comment by HonzaMac** [comment]
V6 stable works great in our repository, we just need little adjustments.
Thanks 🎉

**Comment by ST-DDT** [comment]
> V6 stable works great in our repository, we just need little adjustments.

What kind of adjustments? Did some types/methods change from 5.5.3 to v6.0.0?

**Comment by Shinigami92** [comment]
@HonzaMac 

1. We have a fix for that planned here: https://github.com/faker-js/faker/pull/200
2. You should use `import { faker as fakerStatic } from '@faker-js/faker';`, `import FakerLib from 'faker/lib'` should not be available at all, so I assume you just want to load `require(`@faker-js/faker/locales/${locale}`)` and then merge every into one new faker instance constructed manually.

So something like this (_not tested_):
```ts
import { Faker } from '@faker-js/faker';

new Faker({
  locale: 'rndLocale',
  localeFallback: 'en',
  locales: [
    ...require(`@faker-js/faker/locale/${rndLocale}`).locales
  ]
})
```

This could be a workaround for now, but we plan to change stuff in later major versions. But for the next versions we want to concentrate on bug fixes and small features.

**Comment by ST-DDT** [comment]
> 2\. and then merge every into one new faker instance

Why merge it? AFAICT these instances are exactly what they need/re-create. 
require(`@faker-js/faker/locale/${rndLocale}`)

Maybe we should export the locales as well.
@HonzaMac What do you think?

> 2\. `import FakerLib from 'faker/lib'` should not be available at all,

This is the old import from 553 for comparison.

**Comment by Shinigami92** [comment]
> Maybe we should export the locales (definitions) as well.

Yeah yeah, we should, but that means we need to change stuff in our bundling process, and that's something I would like to tackle in v7+
Don't we have an issue to track this? If not, we could open one to track it.

**Comment by Shinigami92** [comment]
@joequincy I really don't understand why, because we exported it as normal and as default

https://github.com/faker-js/faker/blob/c5df7ee507343086a3b35217aa1d44991023537e/src/index.ts#L33-L37

The only thing I could think of would be that esbuild mess up with something :shrug: 
I can promise you, using the new syntax `{ faker }` will be the long time supported one.
I hope we can move to v7 fast...

**Comment by joequincy** [comment]
Yeah, I've updated our imports already and it's an otherwise seamless version bump. I do think either this should be called out in the release notes as a breaking change or the build process should be tweaked so that `require`s continue to work as before for the 6.x line, but I don't have a strong preference which direction to go there. It was just a jarring breakage.

**Comment by Shinigami92** [comment]
We do have the migration guide: https://fakerjs.dev/migration-guide-v5/#tree-shaking
Hopefully this is at least a bit helpful

**Comment by ST-DDT** [comment]
No critical issues with the release have been reported.
We will now proceed with merging PRs for `v6.1 - First Bugfixes`.
